name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_APP_DIR }}
            echo "Pulling latest code..."
            git pull origin main
            echo "Installing dependencies..."
            npm install
            echo "Building project..."
            npm run build
            echo "Restarting PM2 app..."
            pm2 restart task-management-app || pm2 start dist/server.js --name task-management-app
            echo "Deployment finished."
